"""add booking.owner_notified

Revision ID: 379ee94dc59e
Revises: 92c50b3809dc
Create Date: 2026-09-21 14:28:40.760586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379ee94dc59e'
down_revision: Union[str, Sequence[str], None] = '92c50b3809dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A server_default backfills existing rows so the NOT NULL add is safe on a
    # populated table; the default is dropped afterwards so the app controls it.
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_notified', sa.Boolean(), nullable=False, server_default=sa.false()))
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('owner_notified', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('owner_notified')

    # ### end Alembic commands ###
